[package]

name = "splash"
version = "0.0.1"

[profile.dev]
debug = true

[dependencies]
getopts = "0.2"
parser-combinators = "0.5.1"
libc = "*"
lazy_static = "0.1.*"

[dependencies.readline]
git = "https://github.com/evadnoob/rust-readline.git"

[dependencies.nix]
git = "https://github.com/carllerche/nix-rust.git"
