[package]

license = "GPL-3.0"
name = "splash"
readme = "README"
version = "0.0.1"

[profile.dev]
debug = true

[dependencies]
combine = "^1.2"
getopts = "^0.2"
lazy_static = "^0.1.15"
libc = "*"
nix = "^0.4.2"
readline = "^0.0.11"
